#!/bin/sh
## push.sh for push in /home/marie-_j/rendu
##
## Made by jean-denis marie-sainte
## Login   <marie-_j@epitech.net>
##
## Started on  Mon Oct 20 15:09:43 2014 jean-denis marie-sainte
## Last update Sun Mar 20 17:06:05 2016 Jean-Denis Marie-Sainte
##

#drep=$(pwd)
# cd ~/rendu/$1

find -type f \( -name "*~" -o -name "#*#" -o  -name "*.o" \) -delete

#cd $drep

git add -A :/

echo 'Commit :'

read a

git commit -am "$a"

git push origin master
